spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_rate_consumer_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: currency-rate-consumer
server:
  port: 8070
