spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_rate_downloader_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: currency-rate-downloader
server:
  port: 8090
bnb:
  url:
    bg: 'https://www.bnb.bg/Statistics/StExternalSector/StExchangeRates/StERForeignCurrencies/index.htm?download=xml&search=&lang=BG'
    en: 'https://www.bnb.bg/Statistics/StExternalSector/StExchangeRates/StERForeignCurrencies/index.htm?download=xml&search=&lang=EN'
ws:
  topic:
    name: '/topic/notification'
